---
title: "The Effects of Adaptive Eating Behaviors on Weight Loss of Physically Disabled
Children and Adolescents"
subtitle: ""
author: "Cui, Tianxiang (YC273132)"
institute: "Department of Psychology, University of Macau"
date: "2023.04.03"
output: 
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false

---
class: inverse, center, middle

# Introduction

---

# Obesity

Obesity is rapidly growing in both developed and developing countries (Arroyo-Johnson & Mincey, 2016)


--

Obesity boosts the risk of developing... 

--

**physical health** problems 
  
- **cancer** (Calle & Kaaks, 2004)
- **type 2 diabetes** (Stein & Colditz, 2004)
- **cardiovascular disease** (Field et al., 2001)

--

**mental health** problems
  
- **depression** (Stunkard et al., 2003)
- **low self-esteem** (Franklin et al., 2006)
- **body dissatisfaction and eating disorders** (Brownell & Walsh, 2017; He et al., 2017)



???

the presentation starts from obesity

---

# The prevalence of obesity

Obesity has increased in over 70 countries from 1980 to 2015, and continues to rise in most countries. (The GBD 2015 Obesity Collaborators, 2017).

--

China has seen a dramatic increase in obesity among adults, especially among men (Mi et al., 2015).

--

- an annual cost of 24.35 billion RMB or 2.46% of the nation’s healthcare expenditure due to the increasing obesity rate (Qin & Pan, 2016).


---

# Obesity & physically disabled people

Physically disabled children and adolescents have a higher rate of obesity compared to their non-disabled peers (Neter et al., 2011)

--

Reasons for the higher obesity rate

--

- It is difficult for them to complete enough physical activities and access healthy diets and exercise facilities, as they often come from low-income families (Emerson et al., 2010; Rimmer & Rowland, 2008).

--

- Their lack of social activities may lead to feelings of loneliness and result in binge eating or other **maladaptive eating behaviors**, which can trigger obesity. (Reinehr et al., 2010; Warren et al., 2017).

---

#  Adaptive Eating behaviors

- Developing adaptive eating behaviors (e.g., mindful eating and intuitive eating) can positively address obesity-related behaviors, including binge eating and emotional eating (Warren et al., 2017).

--

- Mindful eating and intuitive eating emphasize developing a good relationship with food, being aware of food choice, and recognizing feelings of hunger and fullness (Warren et al., 2017).

--

- Adaptive Eating behaviors can help individuals slow down consumption of a meal and recognize feelings of fullness to better control overeating (Lofgren, 2015).


---

# Why focusing on eating behaviors?

- Physically disabled individuals have more difficulties doing exercises to lose weight compare to non-disabled peers (Rimmer & Rowland, 2008) 

--

- They may experience sense of isolation which can lead to disordered eating behaviors (Warren et al., 2017)

--

- Adaptive eating behaviors focusing on internal feelings and sensations can be a feasible approach for them to reduce obesity.

--

- Previous treatments for obesity in this population didn’t involve these interventions, highlighting the importance of this approach (Matizanadzo & Paudyal, 2021; McPherson et al., 2014).

---

# Previous interventions

Physical training, exercises, and diet education have not shown significant reductions in BMI or weight (Matizanadzo & Paudyal, 2021; McPherson et al., 2014)

--

- Physical activities and dietary intervention might have failed to be optimally combined (Matizanadzo & Paudyal, 2021)

--

- Studies have had small to medium sample sizes and few involved control group

--

- Previous research has lacked long-term interventions, with most evaluations being conducted less than three months after the interventions (McPherson et al., 2014)

--

- The importance of parental involvement in children's obesity interventions has been underestimated (Golan & Weizman, 2001)

---

# The present study

- To integrate the theories of mindful eating and intuitive eating, and apply them to physically disabled adolescents in China

--

- This theoretical basis will inform the design of an intervention scheme and manual

--

- The feasibility of the intervention scheme will be verified and revised through pretesting, leading to a final scheme

--

- A cluster randomized control study will evaluate the effect of the scheme in different intervention modes

--

- The short- and long-term effects of the scheme will be evaluated the short- and long-term effects of the scheme, and ultimately guide the development of an obesity intervention guide for physically disabled adolescents

--

- The study hypothesizes that the intervention scheme will show positive effects on children and adolescents with physical disabilities


---
class: inverse, center, middle

# Methods

---

# Participants

Sample size estimation: G*Power

--

Junior high school students from rehabilitation centers, with parents being involved

--

Inclusion and exclusion criteria

- Families will be excluded if the child has an intellectual disability, comorbidities or other health conditions, or is receiving other interventions.

- Medical records will be examined to confirm their physical disability status

- Waist circumferences will be measured to determine whether a participant is obese or not (boys: over 83cm; girls: over 78cm; Wingo et al., 2015)

--

Informed consent

---

# Study design

Preparations

--

- A comprehensive theoretical model

--

- Revise and localize the model 

--

- Scheme and the manual for intervention

--


Pilot study: 6-8 weeks

--

Formal intervention: short- (after 3 months) and long-term (after 1 year)

- mode 1 “regular intervention” (in addition to the health education curriculum and physical activity, intervention scheme will be given)

- mode 2 “integrated intervention” (integrate the intervention scheme into the health education curriculum and physical activity)

- mode 3 “indirect intervention” (adolescents will be given health education curriculum and physical activity only but parents will be given lessons)

- The control group will be assigned a health education curriculum only

---

# Measures

Eating Disorder Symptomatology

- The 12-item Eating Disorder Examination Questionnaire (EDE-QS; Gideon et al., 2016)

Intuitive eating

- The Intuitive Eating Scale-2 (IES-2; Tylka & Kroon Van Diest, 2013)

Mindful eating

- The 17-item Mindful Eating Questionnaire adapted for Children (MEQ-C; Hart et al., 2018)

Waist circumference

The development stage of puberty

- The Chinese version of the self-reported Pubertal Development Scale (Chan et al., 2010)

---

# Data analysis

- Correlational analysis

- One-way analysis of variance

- A repeated measures multivariate analysis of variance

- Intention-to-treat analysis

---

# References

Arroyo-Johnson, C., & Mincey, K. D. (2016). Obesity Epidemiology Worldwide. *Gastroenterology Clinics of North America*, *45*(4), 571–579. https://doi.org/10.1016/j.gtc.2016.07.012

Brownell, K. D., & Walsh, B. T. (2017). *Eating disorders and obesity: A comprehensive handbook*. Guilford Publications.

Calle, E. E., & Kaaks, R. (2004). Overweight, obesity and cancer: Epidemiological evidence and proposed mechanisms. *Nature Reviews Cancer*, *4*(8), 579–591. https://doi.org/10.1038/nrc1408

Chan, N. P. T., Sung, R. Y. T., Nelson, E. A. S., So, H. K., Tse, Y. K., & Kong, A. P. S. (2010). Measurement of Pubertal Status with a Chinese Self-report Pubertal Development Scale. *Maternal and Child Health Journal*, *14*(3), 466–473. https://doi.org/10.1007/s10995-009-0481-2

Emerson, E., Shahtahmasebi, S., Lancaster, G., & Berridge, D. (2010). Poverty transitions among families supporting a child with intellectual disability. *Journal of Intellectual & Developmental Disability*, *35*(4), 224–234. https://doi.org/10.3109/13668250.2010.518562

---

# References

Field, A. E., Coakley, E. H., Must, A., Spadano, J. L., Laird, N., Dietz, W. H., Rimm, E., & Colditz, G. A. (2001). Impact of Overweight on the Risk of Developing Common Chronic Diseases During a 10-Year Period. *Archives of Internal Medicine*, *161*(13), 1581. https://doi.org/10.1001/archinte.161.13.1581

Franklin, J., Denyer, G., Steinbeck, K. S., Caterson, I. D., & Hill, A. J. (2006). Obesity and Risk of Low Self-esteem: A Statewide Survey of Australian Children. *PEDIATRICS*, *118*(6), 2481–2487. https://doi.org/10.1542/peds.2006-0511

Gideon, N., Hawkes, N., Mond, J., Saunders, R., Tchanturia, K., & Serpell, L. (2016). Development and psychometric validation of the EDE-QS, a 12 item short form of the Eating Disorder Examination Questionnaire (EDE-Q). *PLoS One*, *11*(5), e0152744.

Golan, M., & Weizman, A. (2001). Familial approach to the treatment of childhood obesity: Conceptual model. *Journal of Nutrition Education*, *33*(2), 102–107. https://doi.org/10.1016/S1499-4046(06)60173-5

Hart, S. R., Pierson, S., Goto, K., & Giampaoli, J. (2018). Development and initial validation evidence for a mindful eating questionnaire for children. *Appetite*, *129*, 178–185. https://doi.org/10.1016/j.appet.2018.07.010

---

# References

He, J., Cai, Z., & Fan, X. (2017). Prevalence of binge and loss of control eating among children and adolescents with overweight and obesity: An exploratory meta-analysis. *International Journal of Eating Disorders*, *50*(2), 91–103. https://doi.org/10.1002/eat.22661

Lofgren, I. E. (2015). Mindful eating: An emerging approach for healthy weight management. *American Journal of Lifestyle Medicine*, *9*(3), 212–216. https://doi.org/10.1177/1559827615569684

Matizanadzo, J. T., & Paudyal, P. (2021). The delivery of obesity interventions to children and adolescents with physical disabilities: A systematic review. *Journal of Public Health*, fdab096. https://doi.org/10.1093/pubmed/fdab096

McPherson, A. C., Keith, R., & Swift, J. A. (2014). Obesity prevention for children with physical disabilities: A scoping review of physical activity and nutrition interventions. *Disability and Rehabilitation*, *36*(19), 1573–1587. https://doi.org/10.3109/09638288.2013.863391

Mi, Y.-J., Zhang, B., Wang, H.-J., Yan, J., Han, W., Zhao, J., Liu, D.-W., & Tian, Q.-B. (2015). Prevalence and Secular Trends in Obesity Among Chinese Adults, 1991−2011. *American Journal of Preventive Medicine*, *49*(5), 661–669. https://doi.org/10.1016/j.amepre.2015.05.005

---

# References

Neter, J. E., Schokker, D. F., de Jong, E., Renders, C. M., Seidell, J. C., & Visscher, T. L. S. (2011). The Prevalence of Overweight and Obesity and Its Determinants in Children with and without Disabilities. *The Journal of Pediatrics*, *158*(5), 735–739. https://doi.org/10.1016/j.jpeds.2010.10.039

Qin, X., & Pan, J. (2016). The Medical Cost Attributable to Obesity and Overweight in China: Estimation Based on Longitudinal Surveys: Medical Cost Attributable to Obesity and Overweight in China. *Health Economics*, *25*(10), 1291–1311. https://doi.org/10.1002/hec.3217

Reinehr, T., Dobe, M., Winkel, K., Schaefer, A., & Hoffmann, D. (2010). Obesity in Disabled Children and Adolescents. *Deutsches Aerzteblatt Online*. https://doi.org/10.3238/arztebl.2010.0268

Rimmer, J. A., & Rowland, J. L. (2008). Physical activity for youth with disabilities: A critical need in an underserved population. *Developmental Neurorehabilitation*, *11*(2), 141–148. https://doi.org/10.1080/17518420701688649

Stein, C. J., & Colditz, G. A. (2004). The Epidemic of Obesity. *The Journal of Clinical Endocrinology & Metabolism*, *89*(6), 2522–2525. https://doi.org/2016092613284600882

---

# References

Stunkard, A. J., Faith, M. S., & Allison, K. C. (2003). Depression and obesity. *Biological Psychiatry*, *54*(3), 330–337. https://doi.org/10.1016/S0006-3223(03)00608-5

The GBD 2015 Obesity Collaborators. (2017). Health Effects of Overweight and Obesity in 195 Countries over 25 Years. *New England Journal of Medicine*, *377*(1), 13–27. https://doi.org/10.1056/NEJMoa1614362

Tylka, T. L., & Kroon Van Diest, A. M. (2013). The Intuitive Eating Scale-2: Item refinement and psychometric evaluation with college women and men. *Journal of Counseling Psychology*, *60*(1), 137–153. https://doi.org/10.1037/a0030893

Warren, J. M., Smith, N., & Ashwell, M. (2017). A structured literature review on the role of mindfulness, mindful eating and intuitive eating in changing eating behaviours: Effectiveness and associated potential mechanisms. *Nutrition Research Reviews*, *30*(2), 272–283. https://doi.org/10.1017/S0954422417000154

Wingo, B. C., Mehta, T., Qu, P., Vogel, L. C., & Rimmer, J. H. (2015). Exploratory Study Examining Clinical Measures of Adiposity Risk for Predicting Obesity in Adolescents with Physical Disabilities. *American Journal of Physical Medicine & Rehabilitation*, *94*(8), 585–594. https://doi.org/10.1097/PHM.0000000000000323





---
class: inverse, center, middle

# Thanks!

